name: build with internal SQLite
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        build:
          - {
            os: ubuntu-latest,
            preset: ninja,

          }
          - {
            os: macos-latest,
            preset: xcode,

          }
          - {
            os: windows-2022,
            preset: msvc22,

          }
    runs-on: ${{ matrix.build.os }}
    steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.30.0"  # <--= optional, use most recent 3.25.x version
        ninjaVersion: "^1.11.1"  # <--= optional, use most recent 1.x version
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup MSVC
      if: startsWith(matrix.build.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
    - name: Configure project
      run:  cmake --preset ${{ matrix.build.preset }} -DPROJECT_ADDONS='add-on/fetch-dependencies' -Dsl3_USE_INTERNAL_SQLITE3=ON
    - name: Build project
      run:  cmake --build --preset ${{ matrix.build.preset }}-release --parallel --verbose
    - name: Run unit test
      run:  ctest --preset ${{ matrix.build.preset }}-release --parallel


